import { expect, test, type Page, type Response } from '@playwright/test';
import fs from 'node:fs/promises';
import type { EvaluateResponse } from '../src/api/types';

// Real browser -> Cognito -> AgentCore -> public model metadata / AWS pricing.
// No intercepted responses or assumed performance. Authentication state is private,
// outside the repository. Traces are disabled because they can contain tokens.
const SITE = process.env.EDDIE_SITE_URL ?? '';
const AUTH_STATE = process.env.EDDIE_AUTH_STATE;
test.skip(!SITE || !AUTH_STATE, 'Provide the demo URL and an ephemeral real sign-in state.');
test.use({ storageState: AUTH_STATE, trace: 'off', actionTimeout: 20_000 });

function isAction(response: Response, action: string): boolean {
  if (!response.url().includes('/invocations')) return false;
  try { return response.request().postDataJSON()?.action === action; }
  catch { return false; }
}

async function resultOf<T>(response: Response): Promise<T> {
  expect(response.status()).toBe(200);
  const text = await response.text();
  if (response.headers()['content-type']?.includes('text/event-stream')) {
    const frames = text.split('\n').filter((line) => line.startsWith('data:'))
      .map((line) => JSON.parse(line.slice(5).trim()));
    expect(frames.filter((frame) => frame.event === 'error')).toEqual([]);
    const result = frames.find((frame) => frame.event === 'result');
    expect(result?.ok).toBe(true);
    return result.result as T;
  }
  const envelope = JSON.parse(text);
  expect(envelope.ok).toBe(true);
  return envelope.result as T;
}

async function section(page: Page, name: string) {
  const tab = page.getByRole('tab', { name, exact: true });
  await tab.click();
  await expect(tab).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('tabpanel', { name, exact: true })).toBeVisible();
}

test('a support team can explore, compare and score supplied answers without a wizard', async ({ page }) => {
  test.setTimeout(300_000);
  const evidence: Record<string, unknown> = {
    site: SITE,
    checkedAt: new Date().toISOString(),
    scenario: 'Support-ticket classification and draft replies for human review',
    planningInputs: true,
    scoreInputs: 'Two deliberately supplied test responses; not generated by a model',
    workloadResourcesCreated: false,
  };
  const errors: string[] = [];
  const evaluationRequests: unknown[] = [];
  const actions: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('request', (request) => {
    if (!request.url().includes('/invocations')) return;
    try {
      const body = request.postDataJSON();
      actions.push(body.action);
      if (body.action === 'evaluate') evaluationRequests.push(body.payload);
    } catch { /* Never record authentication headers. */ }
  });
  async function capture(name: string) {
    await fs.writeFile(test.info().outputPath(`${name}.txt`), await page.locator('body').innerText());
    await page.screenshot({ path: test.info().outputPath(`${name}.png`), fullPage: true });
  }
  async function save() {
    await fs.writeFile(test.info().outputPath('evidence.json'), JSON.stringify({
      ...evidence, errors, actions, evaluationRequests,
    }, null, 2));
  }

  const config = await (await page.request.get(`${SITE}/config.json`)).json();
  evidence.releaseId = config.releaseId;
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${SITE}/requirements`);
  await expect(page.getByRole('heading', { name: 'Your AI project', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'All settings', exact: true }).click();
  await page.getByRole('button', { name: 'Reset to defaults', exact: true }).click();
  await page.getByRole('button', { name: 'Back to overview', exact: true }).click();
  await expect(page.getByText('You haven’t chosen one yet', { exact: true })).toBeVisible();
  await capture('01-start-with-your-task');
  await page.getByRole('textbox', { name: 'Your goal', exact: true }).fill(
    'Classify incoming support requests and draft concise replies for a person to review.'
  );
  await page.getByRole('textbox', { name: 'What would a good answer look like?', exact: true }).fill(
    'Correct ticket category in at least 95% of representative examples; replies need human review.'
  );
  await page.getByRole('button', { name: /^When will people use it\?/ }).click();
  await page.getByRole('option', { name: 'Available all the time', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Comparison period in days', exact: true }).fill('30');
  await page.getByRole('spinbutton', { name: 'Hosting budget in USD', exact: true }).fill('2000');
  await page.getByRole('button', { name: 'Usage details — if you know them', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Requests during this period', exact: true }).fill('10000');
  await page.getByRole('spinbutton', { name: 'Requests at the same time', exact: true }).fill('4');
  await page.getByRole('spinbutton', { name: 'Average input tokens', exact: true }).fill('1000');
  await page.getByRole('spinbutton', { name: 'Average output tokens', exact: true }).fill('80');
  await page.getByRole('checkbox', { name: 'I have a response-time target', exact: true }).check();
  await page.getByRole('spinbutton', { name: 'Response target in seconds', exact: true }).fill('5');
  await expect(page.getByRole('checkbox', { name: 'Include the first request after an idle period', exact: true })).toBeChecked();

  // Nothing must require an earlier section to be marked complete.
  await section(page, 'Tests');
  await page.getByRole('textbox', { name: 'Question or task', exact: true }).fill('Please explain this charge.');
  await page.getByRole('textbox', { name: 'Example 1 expected answer', exact: true }).fill('billing');
  await page.getByRole('textbox', { name: 'Example 1 actual answer', exact: true }).fill('billing');
  await section(page, 'Models & sources');
  await page.getByRole('textbox', { name: 'Hugging Face model source', exact: true }).fill('Qwen/Qwen2.5-7B-Instruct');
  const inspected = page.waitForResponse((response) => isAction(response, 'inspect_model'));
  await page.getByRole('button', { name: 'Read model details', exact: true }).click();
  const model = await resultOf<Record<string, unknown>>(await inspected);
  expect(model.ok).toBe(true);
  expect(model.revision).toMatch(/^[a-f0-9]{40}$/);
  await expect(page.getByText('Model information read from Qwen/Qwen2.5-7B-Instruct', { exact: true })).toBeVisible();
  expect(evaluationRequests).toHaveLength(0);
  evidence.inspection = model;
  await capture('02-model-details-read');

  async function compare(label: string, trigger: () => Promise<unknown>) {
    const count = evaluationRequests.length;
    const pending = page.waitForResponse((response) => isAction(response, 'evaluate'));
    await trigger();
    const result = await resultOf<EvaluateResponse>(await pending);
    await expect(page.getByTestId('comparison-summary')).toBeVisible();
    expect(evaluationRequests).toHaveLength(count + 1);
    expect(result.checksStipulated).toBe(false);
    expect(result.winner).toBeNull();
    expect(result.qualification?.performanceMeasured).toBe(false);
    expect(result.qualification?.benchmarkRunIds).toEqual([]);
    expect(result.evaluatedRequest?.latencyEvidence).toBeNull();
    expect(result.evaluatedRequest?.qualityGoal).toContain('95%');
    expect(result.evaluatedRequest?.model.hfCommit).toBe(model.revision);
    expect(result.evaluatedRequest?.workload).toMatchObject({
      requests: '10000', inputTokensPerRequest: '1000', outputTokensPerRequest: '80', concurrency: 4,
    });
    await expect(page.getByText('UNKNOWN', { exact: true })).toHaveCount(0);
    evidence[label] = result;
    await capture(label);
    await save();
    return result;
  }
  const first = await compare('03-30-day-costs', () => page.getByRole('button', {
    name: 'Compare hosting for this model', exact: true,
  }).click());
  expect(first.evaluatedRequest).toMatchObject({
    workload: { horizonHours: '720', billableCopyHours: '720' },
    constraints: { permittedRegions: ['us-east-1'], budgetUsd: '2000' },
    slos: [{ metric: 'p99_latency_ms', thresholdMs: '5000', includeCold: true }],
  });
  expect(first.unresolved.some((candidate) => candidate.gates.some((gate) => gate.name === 'quality' && gate.status === 'UNKNOWN'))).toBe(true);
  expect(Object.values(first.priceFreshness)).not.toContain('UNKNOWN');
  expect(Object.values(first.priceFreshness)).not.toContain('PINNED');

  await section(page, 'Your needs');
  await page.getByRole('spinbutton', { name: 'Hosting budget in USD', exact: true }).fill('100');
  await section(page, 'Compare hosting');
  await expect(page.getByText('Your requirements changed', { exact: true })).toBeVisible();
  await expect(page.getByRole('table', { name: 'Hosting cost estimates and verification status' })).toHaveCount(0);
  const tight = await compare('04-lower-budget', () => page.getByRole('button', {
    name: 'Update comparison', exact: true,
  }).click());
  expect(tight.excluded.every((candidate) => candidate.gates.some((gate) => gate.name === 'budget' && gate.status === 'FAIL'))).toBe(true);
  expect(tight.evaluatedRequest?.constraints.budgetUsd).toBe('100');

  await section(page, 'Your needs');
  await page.getByRole('spinbutton', { name: 'Hosting budget in USD', exact: true }).fill('2000');
  await page.getByRole('button', { name: /^Where may the model run\?/ }).click();
  await page.getByRole('option', { name: 'US West · Oregon', exact: true }).click();
  await page.getByRole('button', { name: /^What should happen first\?/ }).click();
  await page.getByRole('option', { name: 'The first words appear', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Response target in seconds', exact: true }).fill('0.8');
  await section(page, 'Compare hosting');
  const west = await compare('05-region-and-first-response', () => page.getByRole('button', {
    name: 'Update comparison', exact: true,
  }).click());
  expect(west.evaluatedRequest).toMatchObject({
    constraints: { permittedRegions: ['us-west-2'], budgetUsd: '2000' },
    slos: [{ metric: 'ttft_ms', thresholdMs: '800', includeCold: true }],
  });
  expect([...west.unresolved, ...west.excluded].every((candidate) => candidate.region === 'us-west-2')).toBe(true);

  await section(page, 'Tests');
  await expect(page.getByRole('textbox', { name: 'Example 1 expected answer', exact: true })).toHaveValue('billing');
  await page.getByRole('button', { name: 'Add example', exact: true }).click();
  await page.getByRole('group', { name: 'Example 2', exact: true }).getByRole('textbox', { name: 'Question or task', exact: true }).fill('I cannot sign in.');
  await page.getByRole('textbox', { name: 'Example 2 expected answer', exact: true }).fill('account');
  await page.getByRole('textbox', { name: 'Example 2 actual answer', exact: true }).fill('billing');
  const scoring = page.waitForResponse((response) => isAction(response, 'evaluation.score'));
  await page.getByRole('button', { name: 'Score supplied answers', exact: true }).click();
  const score = await resultOf<Record<string, unknown>>(await scoring);
  expect(score).toMatchObject({
    total: 2, passed: 1, failed: 1, matchPercent: '50.00',
    provenance: 'SUPPLIED_OUTPUTS', modelInvoked: false,
    latencyMeasured: false, deploymentQualified: false,
    model: { source: 'Qwen/Qwen2.5-7B-Instruct', revision: model.revision },
  });
  await expect(page.getByRole('heading', { name: 'Answer check results', exact: true })).toBeVisible();
  evidence.answerScore = score;
  await capture('06-supplied-answer-scoring');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export report', exact: true }).click();
  const download = await downloadEvent;
  await download.saveAs(test.info().outputPath('answer-score-export.json'));
  await page.getByRole('textbox', { name: 'Example 2 actual answer', exact: true }).fill('account');
  await expect(page.getByText('These results are for earlier inputs', { exact: true })).toBeVisible();

  // An expert can use keyboard inspection without launching a comparison.
  await page.getByRole('button', { name: 'All settings', exact: true }).click();
  const beforeEnter = evaluationRequests.length;
  const keyboardInspection = page.waitForResponse((response) => isAction(response, 'inspect_model'));
  await page.getByRole('textbox', { name: 'Model source', exact: true }).press('Enter');
  await resultOf(await keyboardInspection);
  expect(evaluationRequests).toHaveLength(beforeEnter);
  await page.getByRole('button', { name: 'Back to overview', exact: true }).click();
  await section(page, 'Tests');
  await expect(page.getByRole('textbox', { name: 'Example 2 actual answer', exact: true })).toHaveValue('account');

  await section(page, 'Models & sources');
  await page.getByRole('button', { name: 'Company or vendor source', exact: true }).click();
  await page.getByRole('textbox', { name: 'Company model source', exact: true }).fill('s3://company-models/support-model/');
  await expect(page.getByText('Private source access needs an adapter', { exact: true })).toBeVisible();
  const catalogPending = page.waitForResponse((response) => isAction(response, 'catalog'));
  await page.getByRole('button', { name: 'Hosted on AWS', exact: true }).click();
  const catalog = await resultOf<Record<string, unknown>>(await catalogPending);
  expect(catalog.region).toBe('us-west-2');
  evidence.catalog = { region: catalog.region, count: catalog.count };
  await expect(page.getByRole('table', { name: 'Native Bedrock models' })).toBeVisible();
  await capture('07-hosted-model-discovery');

  await section(page, 'Deploy & monitor');
  await expect(page.getByRole('heading', { name: 'Try your model on AWS', exact: true })).toBeVisible();
  await capture('08-deployment-capabilities');
  await section(page, 'Your needs');
  await page.reload();
  await expect(page.getByRole('spinbutton', { name: 'Hosting budget in USD', exact: true })).toHaveValue('2000');
  await expect(page.getByRole('spinbutton', { name: 'Response target in seconds', exact: true })).toHaveValue('0.8');
  const dark = page.getByRole('button', { name: 'Switch to dark mode', exact: true });
  if (await dark.count()) await dark.click();
  await capture('09-dark-mode');
  await page.setViewportSize({ width: 390, height: 844 });
  await capture('10-mobile-needs');
  const geometry = await page.evaluate(() => ({
    viewport: innerWidth, document: document.documentElement.scrollWidth,
  }));
  expect(geometry.document).toBeLessThanOrEqual(geometry.viewport + 1);
  await section(page, 'Compare hosting');
  await expect(page.getByTestId('comparison-summary')).toBeVisible();
  await capture('11-mobile-comparison');
  expect(errors).toEqual([]);
  expect(actions).not.toContain('deployment.start');
  expect(actions).not.toContain('plan.approve');
  expect(actions).not.toContain('deployment.invoke');
  evidence.mobileGeometry = geometry;
  evidence.passed = true;
  await save();
});
